apiVersion: v1
kind: Pod
metadata:
  name: webapps
  labels: 
    name: myapp
spec:
  containers:
  - name: webapps
    image: jassyboy/roadmapdevops:V1
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80

