apiVersion: v1
kind: Pod
metadata: 
  name: sampleapp
  labels:
    name: sampleapp
spec:
  containers:
  - name: sampleapp
    image: kizy222/sampleapp:V94
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
<<<<<<< HEAD
      - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: sampleapp
spec:
  type: NodePort
  selector:
    name: sampleapp
  ports:
  - port: 80
    targetPort: 8080
    NodePort: 30000
=======
      - containerPort: 80
>>>>>>> 9c5abb754023dc37f0cd77e3db4d8f75d1866dfb
